apiVersion: serving.kubeflow.org/v1beta1
kind: InferenceService
metadata:
  name: "torchserve"
spec:
  predictor:
    pytorch:
      storageUri: gs://kfserving-examples/models/torchserve/image_classifier
      ports:
       - containerPort: 7070
         name: h2c
         protocol: TCP
