apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: "torchserve-bloom-560m"
spec:
  predictor:
    pytorch:
      storageUri: pvc://model-cache
  nodeName: kube-01            